# Generated by Django 5.2.1 on 2025-09-20 18:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, null=True),
        ),
    ]
