# Generated by Django 5.2.1 on 2025-09-20 18:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
